# -*- coding: utf-8 -*-
import scrapy
from scrapy.contrib.loader import ItemLoader
from scrapy.contrib.loader.processor import TakeFirst, Compose, Join, MapCompose, Identity
import unicodedata
import decimal
from rpost.utils import try_int, cleanUnicode, fixpedcomment, getracepm, mystrip


class HorseItem(scrapy.Item):
    racecourse = scrapy.Field()
    racetime = scrapy.Field()
    racename = scrapy.Field()
    raceclass = scrapy.Field()
    racepm = scrapy.Field()
    racedate = scrapy.Field()
    racedistance = scrapy.Field()
    racegoing = scrapy.Field()
    horsenumber = scrapy.Field()
    horsename = scrapy.Field()
    comment = scrapy.Field()
    todaysWgt_dec = scrapy.Field()
    todaysWgt = scrapy.Field()
    barrier = scrapy.Field()
    dayssincelastrun = scrapy.Field()
    rpRPR = scrapy.Field()
    rpOR = scrapy.Field()
    rpTS = scrapy.Field()
    timestamp = scrapy.Field()
    bestodds = scrapy.Field()
    hage = scrapy.Field()
    WGT1 = scrapy.Field()
    WGT2 = scrapy.Field()
    WGT3 = scrapy.Field()
    WGT4 = scrapy.Field()
    WGT5 = scrapy.Field()
    ClassL1 = scrapy.Field()
    ClassL2 = scrapy.Field()
    ClassL3 = scrapy.Field()
    ClassL4 = scrapy.Field()
    ClassL5 = scrapy.Field()
    L1comment = scrapy.Field()
    L2comment = scrapy.Field()
    L3comment = scrapy.Field()
    L4comment = scrapy.Field()
    L5comment = scrapy.Field()
    L1raceoutcome = scrapy.Field()
    L2raceoutcome = scrapy.Field()
    L3raceoutcome = scrapy.Field()
    L4raceoutcome = scrapy.Field()
    L5raceoutcome = scrapy.Field()
    diomed = scrapy.Field()
    sirecomment = scrapy.Field()
    pedstats = scrapy.Field()
    sirename = scrapy.Field()
    pedigreecomment = scrapy.Field()
    DI = scrapy.Field()
    CD = scrapy.Field()
    Family = scrapy.Field()
    Pedprizemoney = scrapy.Field()
    L1pos = scrapy.Field()
    L2pos = scrapy.Field()
    L3pos = scrapy.Field()
    L4pos = scrapy.Field()
    L5pos = scrapy.Field()


class RacedayItemLoader(ItemLoader):
    default_item_class = HorseItem
    default_output_processor = Compose(TakeFirst(), mystrip)
    ClassL1_out = TakeFirst()
    ClassL2_out = TakeFirst()
    ClassL3_out = TakeFirst()
    ClassL4_out = TakeFirst()
    ClassL5_out = TakeFirst()
    L1comment_out = TakeFirst()
    L2comment_out = TakeFirst()
    L3comment_out = TakeFirst()
    L4comment_out = TakeFirst()
    L5comment_out = TakeFirst()
    racedistance_out = TakeFirst()
    raceclass_out = Join()
    racename_out = Join()
    racetime_out = TakeFirst()
    timestamp_out = TakeFirst()
    sirecomment_out = TakeFirst()
    racegoing_out = TakeFirst()
    age_out = TakeFirst()
    barrier_out = Compose(TakeFirst(), try_int)
    horsenumber_out = Compose(TakeFirst(), try_int)
    dayssincelastrun_out = Compose(TakeFirst(), try_int)
    comment_out = TakeFirst()

    pedstats_out = TakeFirst()
    horsename_out = TakeFirst()
    L1raceoutcome = TakeFirst()
    L2raceoutcome = TakeFirst()
    L3raceoutcome = TakeFirst()
    L4raceoutcome = TakeFirst()
    L5raceoutcome = TakeFirst()
    WGT1 = TakeFirst()
    WGT2 = TakeFirst()
    WGT3 = TakeFirst()
    WGT4 = TakeFirst()
    WGT5 = TakeFirst()
    # default_output_processor = Compose(TakeFirst(), unicode, unicode.strip)
    DI_out = Compose(TakeFirst(), unicode, unicode.strip)
    CD_out = Compose(TakeFirst(), unicode, unicode.strip)
    pedstats_out = Compose(Join(), unicode, unicode.strip, cleanUnicode)
    racename_out = Compose(Join(), unicode, unicode.strip)
    pedigreecomment_out = Compose(TakeFirst(), fixpedcomment)
    pedstats_out = Compose(Join(), unicode, unicode.strip)
    diomed_out = Join()
    rpOR_out = Compose(TakeFirst(), try_int)
    rpRPR_out = Compose(TakeFirst(), try_int)
    RPTS_out = Compose(TakeFirst(), try_int)
    comment_out = TakeFirst()
    racecourse_out = Compose(TakeFirst(), unicode, unicode.strip)

    sirename_out = Compose(TakeFirst(), unicode, unicode.strip)
    racedate_out = Compose(TakeFirst(), unicode, unicode.strip)
    racetime_out = Compose(TakeFirst(), unicode, unicode.strip)
    racecourse_out = Compose(TakeFirst(), unicode, unicode.strip)
    sirecomment_out = Compose(TakeFirst(), unicode, unicode.strip)
    racedistance_out = Compose(TakeFirst(), unicode, unicode.strip)
    raceclass_out = Compose(Join(), unicode, unicode.strip)
    racepm_out = Compose(TakeFirst(), unicode, unicode.strip, getracepm)
    L1raceoutcome = Compose(TakeFirst(), unicode, unicode.strip)
    L2raceoutcome = Compose(TakeFirst(), unicode, unicode.strip)
    L3raceoutcome = Compose(TakeFirst(), unicode, unicode.strip)
    L4raceoutcome = Compose(TakeFirst(), unicode, unicode.strip)
    L5raceoutcome = Compose(TakeFirst(), unicode, unicode.strip)